### ISSUE TITLE
Rate limiting 

### ISSUE THREAD

**Issue by msmelodypink** [pivotal-cf/team-edition#1]
While sending large batch requests team edition fails.  Can we create a backoff and retry for longer sets of data to tracker?

@supertopher @mkocher

![screen shot 2016-12-08 at 10 10 31 am](https://cloud.githubusercontent.com/assets/13738254/21024785/a7f269f8-bd3a-11e6-975e-c78f6bebbff8.png)

**Comment by halliwilljustin** [comment]
@msmelodypink Can I close this issue?
